version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: devops-tracker-postgres
    environment:
      POSTGRES_DB: issuetracker_db
      POSTGRES_USER: issuetracker
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - devops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U issuetracker -d issuetracker_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Security: No external ports exposed in production
    # ports:
    #   - "5432:5432"

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    container_name: devops-tracker-redis
    volumes:
      - redis_data:/data
    networks:
      - devops-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Security: No external ports exposed in production
    # ports:
    #   - "6379:6379"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops-tracker-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://issuetracker:${POSTGRES_PASSWORD:-your_secure_password}@postgres:5432/issuetracker_db
      JWT_SECRET: ${JWT_SECRET:-your_super_secure_jwt_secret_here_min_32_chars}
      BCRYPT_ROUNDS: 12
      REDIS_URL: redis://redis:6379
      LOG_LEVEL: info
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost}
      RATE_LIMIT_MAX: 100
      RATE_LIMIT_WINDOW: 15
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - devops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # Security: No external ports exposed - only accessible through nginx
    # ports:
    #   - "4000:4000"

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:4000}
        VITE_GRAPHQL_ENDPOINT: /graphql
        VITE_APP_NAME: ${VITE_APP_NAME:-DevOps Node Tracker}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
        VITE_ENABLE_ANALYTICS: ${VITE_ENABLE_ANALYTICS:-false}
        VITE_ENABLE_DEBUG_MODE: ${VITE_ENABLE_DEBUG_MODE:-false}
        VITE_COMPANY_NAME: ${VITE_COMPANY_NAME:-DevOps Node Tracker GmbH}
        VITE_COMPANY_ADDRESS: ${VITE_COMPANY_ADDRESS:-Musterstraße 123, 12345 Musterstadt}
        VITE_COMPANY_PHONE: ${VITE_COMPANY_PHONE:-+49 123 456789}
        VITE_COMPANY_EMAIL: ${VITE_COMPANY_EMAIL:-info@devops-tracker.com}
        VITE_COMPANY_WEBSITE: ${VITE_COMPANY_WEBSITE:-https://devops-tracker.com}
        VITE_CEO_NAME: ${VITE_CEO_NAME:-Max Mustermann}
        VITE_REGISTER_COURT: ${VITE_REGISTER_COURT:-Amtsgericht Musterstadt}
        VITE_REGISTER_NUMBER: ${VITE_REGISTER_NUMBER:-HRB 12345}
        VITE_VAT_ID: ${VITE_VAT_ID:-DE123456789}
        VITE_FOUNDING_YEAR: ${VITE_FOUNDING_YEAR:-2024}
        VITE_DPO_NAME: ${VITE_DPO_NAME:-Max Mustermann}
        VITE_DPO_EMAIL: ${VITE_DPO_EMAIL:-datenschutz@devops-tracker.com}
        VITE_DPO_PHONE: ${VITE_DPO_PHONE:-+49 123 456789}
        VITE_PRIVACY_POLICY_DATE: ${VITE_PRIVACY_POLICY_DATE:-2024-01-01}
        VITE_GITHUB_URL: ${VITE_GITHUB_URL:-}
    container_name: devops-tracker-frontend
    ports:
      - "80:80"
      - "443:443"  # HTTPS port for production
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - devops-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  devops-network:
    driver: bridge
    name: devops-tracker-network 